# Generated by Django 4.1.2 on 2022-10-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="nodes",
            new_name="notes",
        ),
    ]
